### PR TITLE
Get it working

### PR DESCRIPTION
**Pull request by webmsgr**
basically a dev branch 

Requirements to merge:
- [ ] keep the connection alive using heartbeats
- [ ] Receive and parse events
- [ ] Somehow propagate the events to a handler in the HivenClient struct

### CODE REVIEW

**Comment by webmsgr** [comment]
i modifed new_websocket to take in 3 functions, an on open, on message, and on close

**Review by insberr — APPROVED** [review]
Looking good

**Comment by webmsgr** [comment]
until we get more done im keeping this as a draft

**Comment by webmsgr** [comment]
my main goal before merging this is to somehow propagate the events to a handler in the HivenClient struct so the end-user can handle them

**Pull request merged**
